Repository gernsdorfer/ngrx-lite, pull requests merged in 2022-05, with the labels that each got.

#23 Split Store into Store and LoadingStore for better State Support without loading state
  angular.json
  apps/sample-app/project.json
  apps/sample-app/src/app/app.component.html
  apps/sample-app/src/app/app.module.ts
  apps/sample-app/src/app/basic/basic.html
  apps/sample-app/src/app/component-store/basic/basic.component.spec.ts
  apps/sample-app/src/app/component-store/basic/basic.component.ts
  apps/sample-app/src/app/component-store/basic/basic.html
  apps/sample-app/src/app/component-store/custom-actions/custom-action.component.ts
  apps/sample-app/src/app/component-store/custom-actions/custom-action.html
  apps/sample-app/src/app/component-store/global-counter/global-counter-service.ts
  apps/sample-app/src/app/component-store/global-counter/service-counter.html
  apps/sample-app/src/app/component-store/global-counter/storage-from-global-service.component.ts
  apps/sample-app/src/app/component-store/muliple-instances/counter-service.ts
  apps/sample-app/src/app/component-store/muliple-instances/demo-a.component.ts
  apps/sample-app/src/app/component-store/muliple-instances/demo-b.component.ts
  apps/sample-app/src/app/component-store/muliple-instances/demo.html
  apps/sample-app/src/app/component-store/muliple-instances/multiple-instances.component.ts
  apps/sample-app/src/app/component-store/service-counter/counter-service.ts
  apps/sample-app/src/app/component-store/service-counter/service-counter.html
  apps/sample-app/src/app/component-store/service-counter/storage-from-service.component.ts
  apps/sample-app/src/app/component-store/share-actions/example.component.ts
  apps/sample-app/src/app/component-store/share-actions/example.html
  apps/sample-app/src/app/component-store/share-actions/my-effect.effect.ts
  apps/sample-app/src/app/component-store/share-actions/shared-actions.module.ts
  apps/sample-app/src/app/component-store/storage/storage.component.ts
  apps/sample-app/src/app/component-store/storage/storage.html
  apps/sample-app/src/app/custom-actions/custom-action.html
  apps/sample-app/src/app/global-counter/service-counter.html
  apps/sample-app/src/app/loading-effect/loading-effect.component.ts
  apps/sample-app/src/app/loading-effect/loading-effect.html
  apps/sample-app/src/app/loading-store/basic/loading-basic.component.ts
  apps/sample-app/src/app/loading-store/basic/loading-effect.html
  apps/sample-app/src/app/loading-store/default-values/loading-effect.html
  apps/sample-app/src/app/loading-store/default-values/loading-with-default-values.component.ts
  apps/sample-app/src/app/muliple-instances/demo.html
  apps/sample-app/src/app/service-counter/service-counter.html
  apps/sample-app/src/app/share-actions/example.component.ts
  apps/sample-app/src/app/share-actions/example.html
  apps/sample-app/src/app/storage/storage.html
  apps/sample-app/src/index.html
  apps/sample-app/src/styles.css
  libs/store/src/injection-tokens/default-loading-state.token.ts
  libs/store/src/models/client-storage.model.ts
  libs/store/src/models/state.model.ts
  libs/store/src/plugins/client-storage.plugin.spec.ts
  libs/store/src/plugins/client-storage.plugin.ts
  libs/store/src/services/action-creator.ts
  libs/store/src/services/index.ts
  libs/store/src/services/loading-store.service.spec.ts
  libs/store/src/services/loading-store.service.ts
  libs/store/src/services/store-factory.service.spec.ts
  libs/store/src/services/store-factory.service.ts
  libs/store/src/services/store.service.spec.ts
  libs/store/src/services/store.service.ts
  package.json
  yarn.lock
Labels: enhancement

#25 export and fix getDefaultComponentLoadingState
  libs/store/src/services/component-loading-store.service.spec.ts
  libs/store/src/services/component-loading-store.service.ts
  libs/store/src/services/component-store.service.spec.ts
  libs/store/src/services/component-store.service.ts
  libs/store/src/services/index.ts
  libs/store/src/services/loading-store.service.spec.ts
  libs/store/src/services/store-factory.service.spec.ts
  libs/store/src/services/store-factory.service.ts
Labels: bug

#26 update libs
  .stackblitzrc
  angular.json
  apps/doc-app/project.json
  apps/sample-app/project.json
  jest.config.js
  jest.preset.js
  libs/store/project.json
  package.json
  yarn.lock
Labels: dependencies

#28 don't remove store, because of devtools old state problems
  libs/store/src/services/store-factory.service.spec.ts
  libs/store/src/services/store-factory.service.ts
Labels: internal

#29 store form data
  apps/sample-app/src/app/app.component.html
  apps/sample-app/src/app/app.module.ts
  apps/sample-app/src/app/form-store/basic/persist-form.component.spec.ts
  apps/sample-app/src/app/form-store/basic/persist-form.component.ts
  apps/sample-app/src/app/form-store/basic/persist-form.html
  apps/sample-app/src/styles.css
  libs/store/src/injection-tokens/state.token.ts
  libs/store/src/services/component-loading-store.service.spec.ts
  libs/store/src/services/component-loading-store.service.ts
  libs/store/src/services/component-store.service.spec.ts
  libs/store/src/services/component-store.service.ts
  libs/store/src/services/store-factory.service.spec.ts
  libs/store/src/services/store-factory.service.ts
Labels: enhancement

#30 Refactor devtool sync
  apps/sample-app/src/app/app.component.html
  apps/sample-app/src/app/form-store/basic/persist-form.component.ts
  libs/store/src/services/component-loading-store.service.spec.ts
  libs/store/src/services/component-loading-store.service.ts
  libs/store/src/services/component-store.service.spec.ts
  libs/store/src/services/component-store.service.ts
  libs/store/src/services/store-factory.service.spec.ts
  libs/store/src/services/store-factory.service.ts
Labels: internal

#31 support routing Store
  apps/sample-app/src/app/app.module.ts
  libs/store/src/index.ts
  libs/store/src/router-store/router-service.spec.ts
  libs/store/src/router-store/router-service.ts
  libs/store/src/router-store/router-store.module.spec.ts
  libs/store/src/router-store/router-store.module.ts
  libs/store/src/services/component-store.service.spec.ts
  libs/store/src/services/component-store.service.ts
  libs/store/src/services/store-factory.service.spec.ts
  libs/store/src/services/store-factory.service.ts
Labels: enhancement

#32 Example entitiy
  apps/sample-app/src/app/app-routing.module.ts
  apps/sample-app/src/app/app.component.html
  apps/sample-app/src/app/app.component.ts
  apps/sample-app/src/app/app.module.ts
  apps/sample-app/src/app/component-store/basic/basic.html
  apps/sample-app/src/app/component-store/combine-with-entity/combine-with-entity.component.spec.ts
  apps/sample-app/src/app/component-store/combine-with-entity/combine-with-entity.component.ts
  apps/sample-app/src/app/component-store/combine-with-entity/combine-with-entity.html
  apps/sample-app/src/app/component-store/combine-with-entity/entity-module.ts
  apps/sample-app/src/app/component-store/custom-actions/custom-action.html
  apps/sample-app/src/app/component-store/global-counter/service-counter.html
  apps/sample-app/src/app/component-store/muliple-instances/demo.html
  apps/sample-app/src/app/component-store/service-counter/service-counter.html
  apps/sample-app/src/app/component-store/storage/storage.html
  apps/sample-app/src/app/form-store/basic/persist-form.html
  apps/sample-app/src/app/form-store/persist-form/persist-form.component.spec.ts
  apps/sample-app/src/app/form-store/persist-form/persist-form.component.ts
  apps/sample-app/src/app/form-store/persist-form/persist-form.html
  apps/sample-app/src/app/form-store/persist-form/persist-form.module.ts
  apps/sample-app/src/app/loading-store/basic/loading-effect.html
  apps/sample-app/src/app/loading-store/default-values/loading-effect.html
  apps/sample-app/src/app/shared/ui/card-component.ts
  apps/sample-app/src/app/shared/ui/spinner.ts
  apps/sample-app/src/app/shared/ui/toolbar.ts
  apps/sample-app/src/app/shared/ui/ui.module.ts
  apps/sample-app/src/styles.css
  package.json
  yarn.lock
Labels: documentation

#36 Refactor store factory
  libs/store/src/services/index.ts
  libs/store/src/services/store-factory.service.spec.ts
  libs/store/src/services/store-factory.service.ts
  libs/store/src/services/store.service.spec.ts
  libs/store/src/services/store.service.ts
  libs/store/src/services/stores/component-loading-store.service.spec.ts
  libs/store/src/services/stores/component-loading-store.service.ts
  libs/store/src/services/stores/component-store.service.spec.ts
  libs/store/src/services/stores/component-store.service.ts
Labels: internal

#37 support timeTravel from imported states
  apps/sample-app/src/app/app.module.ts
  libs/store/src/router-store/router-store.module.ts
  libs/store/src/services/action-creator.ts
  libs/store/src/services/store-factory.service.spec.ts
  libs/store/src/services/store-factory.service.ts
  libs/store/src/services/store.service.spec.ts
  libs/store/src/services/store.service.ts
Labels: enhancement

#38 Remove reducer after store destroy (only if no Devtools configured )
  libs/store/src/services/dev-tool-helper.service.ts
  libs/store/src/services/store-factory.service.spec.ts
  libs/store/src/services/store-factory.service.ts
  libs/store/src/services/store.service.spec.ts
  libs/store/src/services/store.service.ts
  libs/store/src/services/stores/component-loading-store.service.spec.ts
  libs/store/src/services/stores/component-loading-store.service.ts
  libs/store/src/services/stores/component-store.service.spec.ts
  libs/store/src/services/stores/component-store.service.ts
Labels: enhancement

#39 Fix compare latest TimeTravelState with store state for Update current State
  libs/store/src/services/store.service.spec.ts
  libs/store/src/services/store.service.ts
Labels: bug

#40 add option skip log for create a new store
  libs/store/src/injection-tokens/state.token.ts
  libs/store/src/services/store-factory.service.spec.ts
  libs/store/src/services/store-factory.service.ts
  libs/store/src/services/store.service.ts
  libs/store/src/services/stores/component-loading-store.service.spec.ts
  libs/store/src/services/stores/component-loading-store.service.ts
  libs/store/src/services/stores/component-store.service.spec.ts
  libs/store/src/services/stores/component-store.service.ts
Labels: enhancement

#41 fix empty monitor state
  libs/store/src/services/store.service.spec.ts
  libs/store/src/services/store.service.ts
Labels: bug

#42 fix skip log option for stores with clientOption
  apps/sample-app/src/app/component-store/store-without-loging/store-without-log.component.ts
  libs/store/src/services/store.service.spec.ts
  libs/store/src/services/store.service.ts
Labels: bug

#44 Spelling corrections and tiny fixes
  .github/workflows/ci.yml
  README.md
Labels: documentation

#45 init router store with current url
  libs/store/src/router-store/router-service.ts
Labels: enhancement
